sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=rgdevops123/testapp-travis-ci-deploy
language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  # Unit Test
  - python test.py
after_success:
  - version="$(awk '$2 == "TESTAPP_VERSION" { print $3; exit }' Dockerfile)"
  - docker pull "$IMAGE_NAME" || true
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
  - docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
